/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./DutchAuctionLaunchpad.types";
import * as _1 from "./DutchAuctionLaunchpad.client";
import * as _2 from "./DutchAuctionLaunchpad.message-composer";
import * as _3 from "./DutchAuctionLaunchpad.react-query";
export namespace contracts {
  export const DutchAuctionLaunchpad = { ..._0,
    ..._1,
    ..._2,
    ..._3
  };
}