/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export interface InstantiateMsg {
  accepted_denoms: string[];
  admin: string;
  auction_creation_fee: Coin;
  max_auction_duration: number;
  min_seconds_until_auction_start: number;
}
export interface Coin {
  amount: Uint128;
  denom: string;
}
export type ExecuteMsg = {
  create_auction: {
    end_price: Uint128;
    end_time: Timestamp;
    in_denom: string;
    offered_asset: Coin;
    start_time: Timestamp;
    starting_price: Uint128;
  };
} | {
  bid: {
    auction_id: number;
  };
} | {
  change_params: {
    accepted_denoms?: string[] | null;
    admin?: string | null;
    auction_creation_fee?: Coin | null;
    max_auction_duration?: number | null;
    min_seconds_until_auction_start?: number | null;
  };
} | {
  cancel_auction: {
    auction_id: number;
  };
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type QueryMsg = {
  auctions: {
    limit?: number | null;
    start_after?: number | null;
  };
} | {
  auction: {
    auction_id: number;
  };
} | {
  params: {};
};
export interface Auction {
  creator: string;
  end_price: Uint128;
  end_time: Timestamp;
  in_denom: string;
  offered_asset: Coin;
  remaining_amount: Uint128;
  start_time: Timestamp;
  starting_price: Uint128;
}
export type ArrayOfTupleOfUint8AndAuction = [number, Auction][];
export type Addr = string;
export interface Params {
  accepted_denoms: string[];
  admin: Addr;
  auction_creation_fee: Coin;
  max_auction_duration: number;
  min_seconds_until_auction_start: number;
}